const types = {
   CHANGE_THEME: 'CHANGE_THEME',
   CHANGE_MODEL: 'CHANGE_MODEL',
   CHANGE_MAX_TOKENS: 'CHANGE_MAX_TOKENS',
   CHANGE_TEMPERATURE: 'CHANGE_TEMPERATURE',
   CHANGE_SIZE: 'CHANGE_SIZE',
   CHANGE_AMOUNT: 'CHANGE_AMOUNT',
   CHANGE_MODE: 'CHANGE_MODE',
   RESET: 'RESET',
}

export default types
