const types = {
   LOADING: 'LOADING',
   SEND_PROMPT_MODE1: 'SEND_PROMPT_MODE1',
   SEND_PROMPT_MODE0: 'SEND_PROMPT_MODE0',
   RECEIVE_COMPLETION: 'RECEIVE_COMPLETION',
   RECEIVE_IMAGE: 'RECEIVE_IMAGE',
}

export default types
